server:
  port: 9091
  tomcat:
    uri-encoding: utf-8
logging:
  file: /app/log/aifence.log
  level:
    root: error
    cloud: debug
spring:
  redis:
    timeout: 1000
    commandTimeout: 5000
    host: 192.168.1.128
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-active: 200
        #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20
        # 连接池中的最大空闲连接
        min-idle: 5
        #连接池中的最小空闲连接
        max-wait: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
#    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
